# -*- coding: utf-8 -*-
"""HC_step3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLEPN8oaVxIqUd21apKsNnNs4GitTRCM

#Deep Learning
"""

import pandas as pd
df= pd.read_csv("/content/df.csv") # import df dataset first

print(df.head(3).to_markdown())

df=df.drop(['LOS_Days', 'Patient_Satisfaction_Score','High_Risk_Flag','Expected_LOS_Category'], axis = 1)
print(df.head(3).to_markdown())

"""#4.3 Deep learning using keras

for 'Risk Score'
"""

target = df['Risk_Score']
data = df.drop('Risk_Score', axis=1)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Load California Housing dataset
X, y = data, target

# Split data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize features (Standardization)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define a simple neural network
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # Hidden layer
    layers.Dense(32, activation='relu'),  # Another hidden layer
    layers.Dense(16, activation='relu'),  # Another hidden layer
    layers.Dense(8, activation='relu'),  # Another hidden layer
    layers.Dense(2, activation='relu'),  # Another hidden layer
    layers.Dense(1)  # Output layer (regression)
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Evaluate the model
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test MAE: {test_mae:.4f}")

# Predict on test samples
predictions = model.predict(X_test[:5])
print("Sample Predictions:", predictions.flatten())

"""### 4.3.2. Changing the epoch = 20"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Load California Housing dataset
X, y = data, target

# Split data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize features (Standardization)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define a simple neural network
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # Hidden layer
    layers.Dense(32, activation='relu'),  # Another hidden layer
    layers.Dense(16, activation='relu'),  # Another hidden layer
    layers.Dense(8, activation='relu'),  # Another hidden layer
    layers.Dense(2, activation='relu'),  # Another hidden layer
    layers.Dense(1)  # Output layer (regression)
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Train the model
model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

# Evaluate the model
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test MAE: {test_mae:.4f}")

# Predict on test samples
predictions = model.predict(X_test[:5])
print("Sample Predictions:", predictions.flatten())

"""### 4.3.3. Changing the epoch = 30"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Load California Housing dataset
X, y = data, target

# Split data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize features (Standardization)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define a simple neural network
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # Hidden layer
    layers.Dense(32, activation='relu'),  # Another hidden layer
    layers.Dense(16, activation='relu'),  # Another hidden layer
    layers.Dense(8, activation='relu'),  # Another hidden layer
    layers.Dense(2, activation='relu'),  # Another hidden layer
    layers.Dense(1)  # Output layer (regression)
])

# Compile the model
#optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Train the model
model.fit(X_train, y_train, epochs=30, batch_size=32, validation_data=(X_test, y_test))

# Evaluate the model
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test MAE: {test_mae:.4f}")

# Predict on test samples
predictions = model.predict(X_test[:5])
print("Sample Predictions:", predictions.flatten())

"""### 4.3.2. Changing the epoch = 100"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Load California Housing dataset
X, y = data, target

# Split data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize features (Standardization)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define a simple neural network
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # Hidden layer
    layers.Dense(32, activation='relu'),  # Another hidden layer
    layers.Dense(16, activation='relu'),  # Another hidden layer
    layers.Dense(8, activation='relu'),  # Another hidden layer
    layers.Dense(2, activation='relu'),  # Another hidden layer
    layers.Dense(1)  # Output layer (regression)
])

# Compile the model
#optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

# Evaluate the model
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test MAE: {test_mae:.4f}")

# Predict on test samples
predictions = model.predict(X_test[:5])
print("Sample Predictions:", predictions.flatten())

"""### We stop the exploration here as the mae starts to increase.

Check points:
1. Early stopping
2. Epoch print log customise print after each 100 epoch
3. Learning rate: data learning rate to decided: slow or faster
Learning rate faster to maximum till 10, however, accuracy will be missed.

Factor = 0.5  -> 0.;

patience = 2;

min_lr = 1e-6   -> 10

## We experience the problem of overfitting. Nevertheless, we know that the dataset is artificially created, so there is a drawback may arise.

##4.4.  Logging for the same model using Keras

Dependent variable : 'Risk Score' (Continuous)
"""

X.shape

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import Callback, ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
import numpy as np

X = data
y = target

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

# ---------------------------
# 2. Define the model
# ---------------------------
model = Sequential([
    Dense(32, activation='relu', input_shape= (X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')

# ---------------------------
# 3. Custom Logger Callback
# ---------------------------
class MyLogger(Callback):
    def on_epoch_end(self, epoch, logs=None):
        print(f"✅ Epoch {epoch+1}: Loss={logs['loss']:.4f}, Val Loss={logs['val_loss']:.4f}")

# ---------------------------
# 4. Checkpoint Callback
# ---------------------------
checkpoint = ModelCheckpoint(
    filepath='best_model.h5',
    monitor='val_loss',
    save_best_only=True,
    mode='min',
    verbose=1
)

# ---------------------------
# 5. Early Stopping Callback
# ---------------------------
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,          # stop after 3 epochs without improvement
    restore_best_weights=True
)

# ---------------------------
# 6. Reduce Learning Rate Callback
# ---------------------------
reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,          # reduce LR by half
    patience=2,          # wait for 2 epochs without improvement
    min_lr=1e-6
)

# ---------------------------
# 7. Train model with all callbacks
# ---------------------------
model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=20,
    callbacks=[MyLogger(), checkpoint, early_stop, reduce_lr]
)

"""#4.4. Deep learning using Keras
for the Categorical dependent variables - High Risk Flag
"""

import pandas as pd
df= pd.read_csv("/content/df.csv") # import df dataset first
print(df.tail(3).to_markdown())
print("-"*50)
print(df.info())

df['High_Risk_Flag'].dtype

# Change to categorical data type
df['High_Risk_Flag'] = df['High_Risk_Flag'].astype("category")

target= df['High_Risk_Flag']
data = df.drop(['Risk_Score','High_Risk_Flag', 'LOS_Days', 'Patient_Satisfaction_Score', 'Expected_LOS_Category'], axis=1)

import pandas as pd
data = pd.DataFrame(data).to_numpy()
target = pd.Series(target).to_numpy()

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler

# Step 1: Generate synthetic binary classification data
X, y = data, target

# Step 2: Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Standardize
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 4: Build logistic regression model in Keras
model = keras.Sequential([
    keras.Input(shape=(X_train.shape[1],)),   # input layer
    layers.Dense(1, activation='sigmoid')     # output layer
])

# Step 5: Compile
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Step 6: Train
model.fit(X_train, y_train, epochs=100, verbose=1, validation_data=(X_test, y_test))

# Step 7: Evaluate
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler

# Step 1: Generate synthetic binary classification data
X, y = data, target

# Step 2: Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Standardize
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 4: Build logistic regression model in Keras
model = keras.Sequential([
    keras.Input(shape=(X_train.shape[1],)),   # input layer
    layers.Dense(1, activation='relu'),     # output layer
    layers.Dense(1, activation='sigmoid'),     # output layer
])

# Step 5: Compile
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Step 6: Train
model.fit(X_train, y_train, epochs=100, verbose=1, validation_data=(X_test, y_test))

# Step 7: Evaluate
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

"""##4.4.2. Increasing neuron/ hidden layers from 1 to 3"""

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler

# Step 1: Generate synthetic binary classification data
X, y = data, target

# Step 2: Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Standardize
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 4: Build logistic regression model in Keras
model = keras.Sequential([
    keras.Input(shape=(X_train.shape[1],)),   # input layer
    layers.Dense(64, activation='relu'),     # output layer
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')# output layer
])

# Step 5: Compile
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Step 6: Train
model.fit(X_train, y_train, epochs=100, verbose=1, validation_data=(X_test, y_test))

# Step 7: Evaluate
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

"""## 4.5. Logging using Keras for Categorical depedent variable

Dependent variable: High Risk Flag
"""

import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import Callback, ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
import numpy as np


X = pd.DataFrame(data).to_numpy().astype(np.float32)
y = pd.Series(target).to_numpy().astype(np.int32)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

# ---------------------------
# 2. Define the model
# ---------------------------
model = Sequential([
    Dense(32, activation='relu', input_shape= (X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(1,activation = 'sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# ---------------------------
# 3. Custom Logger Callback
# ---------------------------
class MyLogger(Callback):
    def on_epoch_end(self, epoch, logs=None):
        print(f"✅ Epoch {epoch+1}: Loss={logs['loss']:.4f}, Val Loss={logs['val_loss']:.4f}")

# ---------------------------
# 4. Checkpoint Callback
# ---------------------------
checkpoint = ModelCheckpoint(
    filepath='best_model.h5',
    monitor='val_loss',
    save_best_only=True,
    mode='min',
    verbose=1
)

# ---------------------------
# 5. Early Stopping Callback
# ---------------------------
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,          # stop after 3 epochs without improvement
    restore_best_weights=True
)

# ---------------------------
# 6. Reduce Learning Rate Callback
# ---------------------------
reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,          # reduce LR by half
    patience=2,          # wait for 2 epochs without improvement
    min_lr=1e-6
)

# ---------------------------
# 7. Train model with all callbacks
# ---------------------------
model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=20,
    callbacks=[MyLogger(), checkpoint, early_stop, reduce_lr]
)