# -*- coding: utf-8 -*-
"""HC_step2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7KzMsThfLouxsveU7y1rZ0T0SW_xpGl

#Health care Project- step 2

# 2. Diagnosis
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Look for Combined dataset. first upload it"""

df = pd.read_csv('/content/combined_data.csv')
df.isnull().sum()

"""## 2.1. Outlier Treatement"""

import seaborn as sns
sns.boxplot(x=df['Risk_Score'])

import pandas as pd
import matplotlib.pyplot as plt

# Suppose your DataFrame is df
# Step 1: Select numeric columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Step 2: Plot boxplots for all numeric variables
plt.figure(figsize=(15, 8))
df[numeric_cols].boxplot()
plt.xticks(rotation=90)  # Rotate labels for readability
plt.title("Boxplots of Numeric Variables")
plt.show()

df.columns

import pandas as pd
import matplotlib.pyplot as plt

# Step 1: Select the particular varibles of our interest
selected_cols = [
    'LOS_Days',
    'Patient_Satisfaction_Score',
    'Bed_Occupancy_Rate',
    'Comorbidity_Count'
]

#Step 2: Put in dataframe
selected_df = df[selected_cols]

# Step 3: Plot boxplots for all numeric variables
plt.figure(figsize=(15, 8))
selected_df.boxplot()
plt.xticks(rotation=90)  # Rotate labels for readability
plt.title("Boxplots of suspected outliers Variables")
plt.show()

# we check manually if the mean and median are same for the given variables
mean_LOS_Days= df['LOS_Days'].mean()
median_LOS_Days= df['LOS_Days'].median()

print(f"Mean of LOS_Days: {mean_LOS_Days}")
print(f"Median of LOS_Days: {median_LOS_Days}")

# Recaping the outliers by IQR method in case of no other options ( or we find out the root cause and treat it)
Q1 = df['LOS_Days'].quantile(0.25)
Q3 = df['LOS_Days'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['LOS_Days'] < lower_bound) | (df['LOS_Days'] > upper_bound)]
# Replace the outliers
df['LOS_Days'] = df['LOS_Days'].clip(lower=lower_bound, upper=upper_bound)

# we re-plot the boxplot
sns.boxplot(x=df['Risk_Score'])

"""### 2.2. Treated outliers by IQR- caping method for imputing

We could have trimed it, here, we choose this method.
"""

# Generalize it for continuous columns
numeric_cols = df.select_dtypes(include=['int64','float64']).columns

def treat_outliers_iqr(df, numeric_cols):
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        # Print summary
        print(f"{col}: lower={lower_bound:.2f}, upper={upper_bound:.2f}")

        # Clip values
        df[col] = df[col].clip(lower=lower_bound, upper=upper_bound)
    return df

"""## 2.3. Encoding

we have two methods: 1. Labeencoding 2. get_dummies
"""

date_cols = ['Admission_Date', 'Observation_Time', 'Encounter_Date', 'Discharge_Date']
df[date_cols] = df[date_cols].apply(pd.to_datetime)

# Generalize it for categorical columns
cat_cols = df.select_dtypes(include=['object']).columns
print(cat_cols)

#-------------------------------
for col in cat_cols:
    print(f"{col}: {df[col].unique()}")

"""Labelling the categorical variates"""

# Treating the categorical variates
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['High_Risk_Flag'] = le.fit_transform(df['High_Risk_Flag'])
df['Expected_LOS_Category'] = le.fit_transform(df['Expected_LOS_Category'])
df['Hospital_Busyness_Flag'] = le.fit_transform(df['Hospital_Busyness_Flag'])
df['Feedback_Sentiment'] = le.fit_transform(df['Feedback_Sentiment'])
df['Lab_Abnormality_Flag'] = le.fit_transform(df['Lab_Abnormality_Flag'])
df['Admission_Type'] = le.fit_transform(df['Admission_Type'])
df['Feedback_Sentiment'] = le.fit_transform(df['Feedback_Sentiment'])

# Encoding the nominal variates
df = pd.get_dummies(df, columns=['Insurance_Provider'], drop_first=True)
df = pd.get_dummies(df, columns=['Gender'], drop_first=True)
df = pd.get_dummies(df, columns=['Race'], drop_first=True)

"""Convert the datatime variable to continous variable"""

# Length of stay in hours
df['Stay_hours'] = (df['Discharge_Date'] - df['Admission_Date']).dt.total_seconds() / 3600
df['Incubation_hours'] = (df['Encounter_Date'] - df['Admission_Date']).dt.total_seconds() / 3600

# Drop the datetime variables from df
df = df.drop(['Admission_Date', 'Observation_Time', 'Discharge_Date','Encounter_Date'], axis = 1)

df.info()

"""# 2.4. Feature Scaling"""

# Define dependent variables (targets)
dependent_vars = ['Risk_Score', 'LOS_Days',
                  'Patient_Satisfaction_Score',
                  'Severity_Score_Encounter']

# Define independent variables (features)
independent_vars = [col for col in df.columns if col not in dependent_vars]

# Create X (features) and y (target)
X = df[independent_vars].copy()  # use .copy() to avoid SettingWithCopyWarning
y = df[dependent_vars].copy()  # use .copy() to avoid SettingWithCopyWarning

y = df['Risk_Score']   # we choose LOS_Days as our target here

df.info()

# Standardize it
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
num_cols = X.select_dtypes(include=['int64','float64']).columns

# Convert to float first
X[num_cols] = X[num_cols].astype(float)  # so that it does not hatch the warnings.

# Apply scaling safely
X.loc[:, num_cols] = scaler.fit_transform(X[num_cols])

X.info()

"""### dataset 'df' will used for further use. Here, export it conserve the dataset"""

df.to_csv('df.csv', index=False)

# export file for the predictive modeling
Risk_Score_df = pd.concat([X, y], axis=1)
Risk_Score_df.to_csv('Risk_Score_df.csv', index=False)

"""#4. Predictive

### ML for the Risk_Score dependent variable
"""

X.info()

"""# ML models

As the dependent variable is continuous. We take a strategie of ML models

Linear -> Polynomial -> Ridge -> Lasso -> Elasticnet -> SVR

##4.1. Linear Regression
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X = df[independent_vars]
y = df['Risk_Score']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Initialize and train regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

#  Evaluate performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R² Score:", r2)

"""##4.2. Polynomial Regression"""

# polynormial regression
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split


X = df[independent_vars]
y = df['Risk_Score']

# Split dataset into test and train
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create polynomial features (degree=2 for quadratic)
poly = PolynomialFeatures(degree=3, include_bias=False)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# Fit linear regression on polynomial features
model = LinearRegression()
model.fit(X_train_poly, y_train)

# Predictions
y_pred = model.predict(X_test_poly)

# Evaluation
print("R²:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

"""##4.3. Ridge Regression for Risk_Score"""

import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

X = df[independent_vars]
y = df['Risk_Score']

# Split dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- Ridge Regression ---
ridge_model = Ridge(alpha=1.0)   # alpha controls regularization strength
ridge_model.fit(X_train, y_train)
y_pred_ridge = ridge_model.predict(X_test)

print("Ridge Regression R²:", r2_score(y_test, y_pred_ridge))
print("MSE:", mean_squared_error(y_test, y_pred_ridge))

"""##4.4. Lasso Regression"""

import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

X = df[independent_vars]
y = df['Risk_Score']

# Split dataset into test and train
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- Lasso Regression ---
lasso_model = Lasso(alpha=0.1)   # alpha controls regularization strength
lasso_model.fit(X_train, y_train)
y_pred_lasso = lasso_model.predict(X_test)

print("Lasso Regression R²:", r2_score(y_test, y_pred_lasso))
print("MSE:", mean_squared_error(y_test, y_pred_lasso))

"""##4.5. Elasticnet Regression"""

import numpy as np
import pandas as pd
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

X = df[independent_vars]
y = df['Risk_Score']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- ElasticNet Regression ---
elastic_model = ElasticNet(alpha=0.1, l1_ratio=0.5, random_state=42)
elastic_model.fit(X_train, y_train)
y_pred_elastic = elastic_model.predict(X_test)

print("ElasticNet R²:", r2_score(y_test, y_pred_elastic))
print("MSE:", mean_squared_error(y_test, y_pred_elastic))

"""##4.6. SVR"""

import numpy as np
import pandas as pd
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.preprocessing import StandardScaler

# Independent and dependent variables
X = df[independent_vars]
y = df['Risk_Score']

# Scale features
#scaler_X = StandardScaler()
scaler_y = StandardScaler()

#X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y.values.reshape(-1, 1)).ravel()

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y_scaled, test_size=0.2, random_state=42
)

# --- SVR Regression ---
svr_model = SVR(kernel='rbf', C=1.0, epsilon=0.1)
svr_model.fit(X_train, y_train)
y_pred_scaled = svr_model.predict(X_test)

# Inverse transform predictions back to original scale
y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1)).ravel()
y_test_orig = scaler_y.inverse_transform(y_test.reshape(-1, 1)).ravel()

# Evaluation
print("SVR R²:", r2_score(y_test_orig, y_pred))
print("MSE:", mean_squared_error(y_test_orig, y_pred))



"""##5. ML prediction for 'LOS_Days'

As the dependent variable is continuous. We take a strategie of ML models

Linear -> Polynomial -> Ridge -> Lasso -> Elasticnet -> SVR

##5.1. Linear Regression for 'LOS_Days'
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X = df[independent_vars]
y = df['LOS_Days']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Initialize and train regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

#  Evaluate performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R² Score:", r2)

"""##5.2. Ridge regression for LOS_days"""

import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

X = df[independent_vars]
y = df['LOS_Days']

# Split dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- Ridge Regression ---
ridge_model = Ridge(alpha=1.0)   # alpha controls regularization strength
ridge_model.fit(X_train, y_train)
y_pred_ridge = ridge_model.predict(X_test)

print("Ridge Regression R²:", r2_score(y_test, y_pred_ridge))
print("MSE:", mean_squared_error(y_test, y_pred_ridge))

"""##5.3. Lasso Regression for LOS_Days"""

import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

X = df[independent_vars]
y = df['LOS_Days']

# Split dataset into test and train
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- Lasso Regression ---
lasso_model = Lasso(alpha=0.1)   # alpha controls regularization strength
lasso_model.fit(X_train, y_train)
y_pred_lasso = lasso_model.predict(X_test)

print("Lasso Regression R²:", r2_score(y_test, y_pred_lasso))
print("MSE:", mean_squared_error(y_test, y_pred_lasso))

"""##5.4. Elasticnet Regression for LOS_Days"""

import numpy as np
import pandas as pd
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

X = df[independent_vars]
y = df['LOS_Days']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- ElasticNet Regression ---
elastic_model = ElasticNet(alpha=0.1, l1_ratio=0.5, random_state=42)
elastic_model.fit(X_train, y_train)
y_pred_elastic = elastic_model.predict(X_test)

print("ElasticNet R²:", r2_score(y_test, y_pred_elastic))
print("MSE:", mean_squared_error(y_test, y_pred_elastic))

"""##5.5. SVR for LOS_Days"""

import numpy as np
import pandas as pd
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.preprocessing import StandardScaler

# Independent and dependent variables
X = df[independent_vars]
y = df['Risk_Score']

# Scale features
#scaler_X = StandardScaler()
scaler_y = StandardScaler()

#X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y.values.reshape(-1, 1)).ravel()

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y_scaled, test_size=0.2, random_state=42
)

# --- SVR Regression ---
svr_model = SVR(kernel='rbf', C=1.0, epsilon=0.1)
svr_model.fit(X_train, y_train)
y_pred_scaled = svr_model.predict(X_test)

# Inverse transform predictions back to original scale
y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1)).ravel()
y_test_orig = scaler_y.inverse_transform(y_test.reshape(-1, 1)).ravel()

# Evaluation
print("SVR R²:", r2_score(y_test_orig, y_pred))
print("MSE:", mean_squared_error(y_test_orig, y_pred))

"""#6. ML for 'Severity_Score_Encounter'

As the dependent variable is continuous. We take a strategie of ML models

Linear -> Polynomial -> Ridge -> Lasso -> Elasticnet -> SVR
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X = df[independent_vars]
y = df['Patient_Satisfaction_Score']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Initialize and train regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

#  Evaluate performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R² Score:", r2)

"""Mean Squared Error: 2.202643490848169
R² Score: -0.11765345655803872

This shows that the model is not efficient or there are other problems. Either Preprocessing or Correlation between the dependent variables or no enough datasets. We shall come back later here if necessary.
"""