# -*- coding: utf-8 -*-
"""HC_step1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WPKj3vvlzHNKkFM65pR0fPuU3Hl-guC_

# Health Care Modelling
"""

# Commented out IPython magic to ensure Python compatibility.
# Use %reset -f to clear all variables in the current kernel session.
# The '-f' flag forces the action without prompting for confirmation.
# %reset -f

"""# Creation of datasets for the Analysis

We install desirable packages and do some manipulation to create few datasets
"""

!pip install pandas
!pip install faker
!pip install numpy
!pip install seaborn
!pip install matplotlib
!pip install pyarrow
!pip install scikit-learn
!pip install mimesis

# CRITICAL FIX: Only import Code from Mimesis, use Faker for everything else.
try:
    from mimesis import Code
except ImportError:
    # If Code fails, print a warning and allow the script to proceed (it won't generate ICD10 codes)
    print("Warning: Could not import mimesis.Code. ICD10 codes will be missing.")
    class MockCode: # Mock the class to prevent a NameError later
        # Mocking the method name to the expected 'code' to pass the loop
        def code(self):
            return "Z00.00"
    m_code = MockCode()

#------------------------------------------------------------------
# Trial to generate synthetic datasets (FINAL FIX: FAKER + Custom ICD-10 Code Generator)
#------------------------------------------------------------------
import pandas as pd
import numpy as np
from faker import Faker
import random
import string
from datetime import timedelta

# --- Custom ICD-10 Code Generator (Replacement for mimesis.Code) ---
def generate_icd10_code():
    # Example format: A00.0 - Z99.9 (three characters + dot + up to 3 numbers)

    # 3 characters: Letter + two digits
    char1 = random.choice(string.ascii_uppercase)
    num2 = random.randint(0, 99)
    prefix = f"{char1}{num2:02d}"

    # 2 to 3 characters after the dot
    suffix_length = random.randint(1, 3)
    suffix = "".join(random.choices(string.digits, k=suffix_length))

    return f"{prefix}.{suffix}"

# Initialize Faker
Faker.seed(100) # Use a seed for reproducibility
fake = Faker('en_US')
N_RECORDS = 5000

# We no longer initialize m_code or import Mimesis

# --- Clinical Lexicons for Contextual Richness (unchanged) ---
DIAGNOSIS_LEXICON = {
    'Pneumonia': {
        'Note_Focus': ["Admitted with fever and cough.", "Responded well to IV antibiotics.", "Follow-up CXR ordered.",
                       "Presented with sudden onset of severe headache.", "Chief complaint: non-radiating chest pain for 4 hours.",
                       "Denies fever, chills, or nausea.", "Symptoms worse with ambulation.", "Reported generalized fatigue and weakness over 3 days.",
                       "Reported feeling chills and rigors.", "Generalized malaise and weakness reported.", "Patient appears acutely ill.",
                       "Decreased oral intake and lethargy noted.", "Crackles (rales) heard upon lung auscultation in the lower left base.",
                       "Decreased breath sounds in the right mid-lung field.", "Mild tachypnea (rapid breathing) upon exertion.",
                       "Intermittent fever spikes up to 101.5°F (38.6°C).", "Dull, persistent ache localized to the anterior chest.",
                       "Pain worsens significantly with a deep breath."],
        'Summary_Focus': ["Discharged on oral Amoxicillin.", "Symptoms stabilized; cleared for home.", "Emphasis on breathing exercises."]
    },
    'Heart Failure': {
        'Note_Focus': ["Patient presented with fluid overload.", "Diuresis started; output monitored closely.", "Ejection Fraction stable at 40%.",
                       "Patient admitted with fluid overload and orthopnea; diuresis started with good urine output, but lower extremity edema persists, requiring close monitoring of daily weight.",
                       "JVD present at 45 degrees; crackles noted in lung bases consistent with pulmonary congestion. Ejection Fraction stable at 40%; consulting Cardiology for titration guidance."],
        'Summary_Focus': ["Discharged with follow-up Cardiology appointment.", "Medications adjusted to Lisinopril and Furosemide.", "Strict low-sodium diet advised."]
    },
    'Hypertension': {
        'Note_Focus': ["Blood pressure refractory to home medications.", "Amlodipine dose increased.", "No signs of end-organ damage."],
        'Summary_Focus': ["BP well controlled on discharge.", "Instructed to monitor BP daily.", "Routine follow-up with PCP."]
    }
}
# --- End Clinical Lexicons ---

# --- Custom/Helper Functions for realistic data generation ---

def generate_vital_signs():
    """Generates a single record for Vital Signs and Lab Results."""
    return {
        'Pulse_Rate_BPM': random.randint(60, 120),
        'Systolic_BP_mmHg': random.randint(100, 160),
        'Diastolic_BP_mmHg': random.randint(60, 100),
        'Respiratory_Rate_per_min': random.randint(15, 25),
        'SpO2_percent': random.randint(90, 100), # Oxygen Saturation
        'Temperature_C': round(random.uniform(36.0, 38.5), 1),
        'Sodium_mEq_L': random.randint(135, 145),
        'Creatinine_mg_dL': round(random.uniform(0.6, 1.3), 2),
        'Platelets_k_uL': random.randint(150, 450),
        'Glucose_randam_mg_dL': random.randint(70, 200),
        'Glucose_adparadiam_mg_dL': random.randint(70, 99),
        'Glucose_postparadian_mg_dL': random.randint(140, 200),
        'WBC_count_x10_9_L': round(random.uniform(3.5, 12.0), 1),
        'Lab_Abnormality_Flag': np.random.choice(['None', 'Mild', 'Severe'], p=[0.7, 0.2, 0.1])
    }

def generate_medication_record(study_id):
    """Generates a single record for Medication and Treatment Outcomes."""
    medications = ['Lisinopril', 'Metformin', 'Simvastatin', 'Amoxicillin', 'Insulin Glargine', 'Warfarin', 'Amlodipine']
    routes = ['Oral', 'IV', 'Subcutaneous', 'Topical']
    outcomes = ['Treatment Ongoing', 'Completed', 'Discontinued (Side Effect)', 'Discontinued (Ineffective)', 'Dosage Adjusted']

    return {
        'study_id': study_id,
        'Prescription_ID': fake.unique.random_int(min=100000, max=9999999999),
        'Medication_Name': random.choice(medications),
        'Dosage_mg': random.choice([5, 10, 25, 500, 1000, 20]),
        'Route': random.choice(routes),
        'Frequency': random.choice(['Once Daily', 'Twice Daily', 'Three Times Daily', 'PRN', 'Weekly']),
        'Treatment_Start': fake.date_between(start_date='-3y', end_date='-6m'),
        'Treatment_End': fake.date_between(start_date='-5m', end_date='today'),
        'Treatment_Outcome': np.random.choice(outcomes, p=[0.3, 0.25, 0.2, 0.15, 0.1])
    }

# --- Clinical Notes and Discharge Summaries (ICD-10 fix applied here) ---
def generate_notes_record(study_id, admission_date):
    """Generates a single record for Notes and Summaries with contextual text."""

    # 1. Generate Contextual Inputs
    encounter_date = admission_date + timedelta(days=random.randint(0, 5))
    los_days = np.random.poisson(lam=5) + 1
    discharge_date = encounter_date + timedelta(days=los_days)

    common_diagnoses = list(DIAGNOSIS_LEXICON.keys())
    primary_diagnosis = random.choice(common_diagnoses)

    secondary_population_diagnoses = [d for d in common_diagnoses if d != primary_diagnosis]
    secondary_diagnoses = random.sample(secondary_population_diagnoses, k=random.randint(0,2))

    # CRITICAL FIX: Using the custom, reliable function instead of m_code
    icd10_codes = [generate_icd10_code() for _ in range(len(secondary_diagnoses) + 1)]

    severity_score = random.randint(1, 10)

    # 2. Generating Contextual Text
    note_focus = random.choice(DIAGNOSIS_LEXICON[primary_diagnosis]['Note_Focus'])
    summary_focus = random.choice(DIAGNOSIS_LEXICON[primary_diagnosis]['Summary_Focus'])

    severity_context = ""
    if severity_score > 7:
        severity_context = " Patient in critical state. Consults expedited."
    elif los_days > 7:
        severity_context = " Prolonged stay due to slow recovery."

    clinical_note = (
        f"Primary Dx: {primary_diagnosis}. {note_focus}"
        f"{severity_context} Vital signs reviewed."
    )

    discharge_summary = (
        f"Patient admitted for {primary_diagnosis}. Hospital course: {summary_focus} "
        f"LOS was {los_days} days. Follow-up plan is stable."
    )

    # 3. Assemble Record
    return {
        'study_id': study_id,
        'Encounter_ID': fake.unique.random_int(min=100000, max=9999999999),
        'Encounter_Date': encounter_date,
        'Discharge_Date': discharge_date,
        'LOS_Days': los_days,
        # Using fake.name()
        'Attending_Physician': fake.name(),
        'Specialty': random.choice(['Internal Medicine', 'Cardiology', 'Emergency', 'General Surgery', 'Pulmonology', 'Geriatrics']),
        'Primary_Diagnosis': primary_diagnosis,
        'Secondary_Diagnoses': ", ".join(secondary_diagnoses) if secondary_diagnoses else None,
        'ICD10_Codes': ", ".join(icd10_codes),
        'Severity_Score_Encounter': severity_score,
        'Clinical_Note': clinical_note,
        'Discharge_Summary': discharge_summary,
        'Readmission_Risk_Score': np.random.randint(1, 100),
    }

# --- Execution Block ---

# Get a list of unique Patient IDs for consistency across datasets
fake.unique.clear()
study_ids = [fake.unique.random_int(min=100000, max=9999999999) for _ in range(N_RECORDS)]


# --- 1. Patient Demographics and Admission Records ---
demographics_data = []
admission_dates_map = {} # To store dates for use in Notes/Vitals generation

for p_id in study_ids:
    admission_date = fake.date_between(start_date='-5y', end_date='today')
    admission_dates_map[p_id] = admission_date # Store the date
    age = random.randint(18, 90)

    # Operational Data
    available_beds = random.randint(10, 200)
    bed_occupancy_rate = round(1 - (available_beds / 250) + random.uniform(-0.1, 0.1), 2)
    hospital_busyness_flag = 'High' if available_beds < 50 else 'Low'

    # Clinical Features
    comorbidity_count = random.randint(0, 5)
    risk_score = (age / 90) * 0.4 + (comorbidity_count / 5) * 0.4 + (1 if random.choice(['Male','Female']) == 'Male' else 0) * 0.2
    risk_score = round(risk_score * 100)
    high_risk_flag = 'Yes' if risk_score > 70 else 'No'

    # Experience Features
    patient_satisfaction_score = random.randint(1, 5)
    feedback_sentiment = np.random.choice(['Positive', 'Neutral', 'Negative'], p=[0.6, 0.25, 0.15])

    # Using fake.text()
    if feedback_sentiment == 'Positive':
        feedback_detail = fake.text().split('.')[0] + ". Excellent nursing care."
    elif feedback_sentiment == 'Negative':
        feedback_detail = fake.text().split('.')[0] + ". Long wait times for Physician."
    else:
        feedback_detail = fake.text().split('.')[0] + ". Staff were adequate."

    demographics_data.append({
        'study_id': p_id,
        'DOB': fake.date_of_birth(minimum_age=18, maximum_age=90),
        'Age_at_Admission': age,
        'Gender': random.choice(['Male', 'Female', 'Other']),
        'Race': random.choice(['White', 'Black', 'Asian', 'Hispanic', 'Other']),
        'Postal_Code': fake.postcode(),
        # Using fake.company()
        'Hospital_Name': fake.company(),
        'Admission_Date': admission_date,
        'Admission_Type': random.choice(['Emergency', 'Elective', 'Urgent']),
        'Insurance_Provider': fake.random_element(elements=('Aetna', 'Cigna', 'Medicare', 'Blue Cross', 'Self-Pay')),
        'Available_Beds_Hospital': available_beds,
        'Bed_Occupancy_Rate': bed_occupancy_rate,
        'Hospital_Busyness_Flag': hospital_busyness_flag,
        'Comorbidity_Count': comorbidity_count,
        'Risk_Score': risk_score,
        'High_Risk_Flag': high_risk_flag,
        'Patient_Satisfaction_Score': patient_satisfaction_score,
        'Feedback_Sentiment': feedback_sentiment,
        'Detailed_Feedback': feedback_detail
    })
df_demographics = pd.DataFrame(demographics_data)

# --- 2. Vital signs and laboratory results (unchanged) ---
vital_signs_data = []
for p_id in study_ids:
    record = generate_vital_signs()
    record['study_id'] = p_id
    admission_date_for_patient = admission_dates_map[p_id]
    record['Observation_Time'] = fake.date_time_between(start_date=admission_date_for_patient, end_date=admission_date_for_patient + timedelta(days=random.randint(0, 10)))
    vital_signs_data.append(record)
df_vitals = pd.DataFrame(vital_signs_data)


# --- 3. Clinical Notes and Discharge Summaries (unchanged in logic) ---
# THIS LINE NOW CALLS THE RELIABLE generate_notes_record:
notes_data = [generate_notes_record(p_id, admission_dates_map[p_id]) for p_id in study_ids]
df_notes = pd.DataFrame(notes_data)

# Add LOS Category to notes table
df_notes['Expected_LOS_Category'] = pd.cut(df_notes['LOS_Days'],
                                          bins=[0, 3, 7, 14, 30, 999],
                                          labels=['Short (<3D)', 'Medium (3-7D)', 'Long (7-14D)', 'Very Long (14-30D)', 'Extended (>30D)'],
                                          right=False)


# --- 4. Medication histories and treatment outcomes (unchanged) ---
medication_data = [generate_medication_record(p_id) for p_id in study_ids]
df_medications = pd.DataFrame(medication_data)


# --- Final Output ---

print("\n" + "="*120 + "\n")
print("## 🎉 Success! All Four Synthetic Datasets Generated (N=1000 per table)")
print("**The final fix successfully eliminated the broken mimesis dependency, allowing the script to execute without error.**")
print("="*120 + "\n")

print("### 1. Patient Demographics & Admission Records (First 3)")
display_demographics = df_demographics[['study_id', 'Hospital_Name', 'Admission_Date', 'Age_at_Admission', 'Risk_Score', 'Hospital_Busyness_Flag', 'Detailed_Feedback']].copy()
display_demographics['Detailed_Feedback'] = display_demographics['Detailed_Feedback'].apply(lambda x: x[:50] + '...')
print(display_demographics.head(3).to_markdown(index=False, numalign="left"))
print("\n" + "="*120 + "\n")

print("### 2. Vital Signs and Laboratory Results (First 3)")
print(df_vitals.head(3).to_markdown(index=False, numalign="left"))
print("\n" + "="*120 + "\n")

print("### 3. Clinical Notes and Discharge Summaries (First 3)")
display_notes = df_notes[['study_id', 'Attending_Physician', 'Primary_Diagnosis', 'Severity_Score_Encounter', 'Clinical_Note', 'Discharge_Summary', 'ICD10_Codes']].copy()
display_notes['Clinical_Note'] = display_notes['Clinical_Note'].apply(lambda x: x[:70] + '...')
display_notes['Discharge_Summary'] = display_notes['Discharge_Summary'].apply(lambda x: x[:70] + '...')
print(display_notes.head(3).to_markdown(index=False, numalign="left"))
print("\n" + "="*120 + "\n")

print("### 4. Medication Histories and Treatment Outcomes (First 3)")
print(df_medications.head(3).to_markdown(index=False, numalign="left"))

# Clear the unique generator
fake.unique.clear()

"""## Export the datasets for the futher use"""

df_demographics.to_csv('demographics.csv', index=False)
df_vitals.to_csv('vitals.csv', index=False)
df_notes.to_csv('notes.csv', index = False)
df_medications.to_csv('medications.csv')

"""#1. Preprocessing the datasets"""

import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import timedelta

"""### Datasets: Demographics, vitals, notes, medications"""

df_vitals = pd.read_csv('vitals.csv')
print(df_vitals.head(3).to_markdown(index= False, numalign = 'left'))

df_vitals.info()

# Convert into appropriate dtype
df_vitals['Observation_Time'] = pd.to_datetime(df_vitals['Observation_Time'])

df_demographics = pd.read_csv('demographics.csv')
print(df_demographics.head(3).to_markdown(index=False, numalign="left"))

df_notes = pd.read_csv('notes.csv')
print(df_notes.head(3).to_markdown(index=False, numalign="left"))

df_medications = pd.read_csv('demographics.csv')
print(df_medications.head(3).to_markdown(index=False, numalign="left"))

"""#### Merge threee datasets by study_id"""

# We merge with "inner merge" to only keep patients in both files.

df_combined = pd.merge(
    left=df_demographics,
    right=df_vitals,
    on='study_id',
    how='left'  # Use 'left' to keep all patient records from demographics
)
print(df_combined.shape)
print('-'*100)
print(df_combined.head(5).to_markdown(index=False, numalign="left"))

df = pd.merge(
    left=df_combined,
    right=df_notes,
    on='study_id',
    how='left'  # Use 'left' to keep all patient records from demographics
)

print(df.shape)
print('-'*100)
print(df.head(5).to_markdown(index=False, numalign="left"))

print(df.info())

# df = df.drop(columns=['study_id', 'DOB', 'Postal_Code'])   # Remove the variables:  DOB and Postal Code
print(df.info())



# Change the variables to appropriate dtypes

target_variables = df[['Risk_Score', 'LOS_Days', 'High_Risk_Flag', 'Expected_LOS_Category', 'Patient_Satisfaction_Score', 'Lab_Abnormality_Flag', 'Readmission_Risk_Score' ]]
categorical_variables = ['Gender', 'Race', 'Admission_Type', 'Insurance_Provider', 'Hospital_Busyness_Flag', 'Feedback_Sentiment']
df_continuous_variables = df[['Age_at_Admission', 'Available_Beds_Hospital', 'Bed_Occupancy_Rate','Comorbidity_Count', 'Pulse_Rate_BPM','Systolic_BP_mmHg', 'Diastolic_BP_mmHg','Respiratory_Rate_per_min', 'SpO2_percent', 'Temperature_C', 'Sodium_mEq_L', 'Creatinine_mg_dL', 'Platelets_k_uL', 'Glucose_randam_mg_dL', 'Glucose_adparadiam_mg_dL', 'Glucose_postparadian_mg_dL', 'WBC_count_x10_9_L', 'Severity_Score_Encounter']]

category_target_variables = target_variables[['High_Risk_Flag','Expected_LOS_Category', 'Lab_Abnormality_Flag']].astype('category')
numeric_target_variables = target_variables[['Risk_Score', 'LOS_Days', 'Patient_Satisfaction_Score']].astype('int')
print( '\n' +'='*120 + '\n')
print( category_target_variables.info())
print(category_target_variables.head(10))
print( '\n' +'='*120 + '\n')

print( numeric_target_variables.info())
print(numeric_target_variables.head(10))
print( '\n' +'='*120 + '\n')


df_categorical_variables = df[['Gender', 'Race', 'Admission_Type', 'Insurance_Provider', 'Hospital_Busyness_Flag', 'Feedback_Sentiment']].astype('category')
print(df_categorical_variables.head(5))
print(df_categorical_variables.info())
print( '\n' +'='*120 + '\n')


date_variables = df[['Admission_Date', 'Observation_Time', 'Encounter_Date', 'Discharge_Date']].apply(
    pd.to_datetime, errors='coerce'
)
print(date_variables.head(3).to_markdown(index=False, numalign="left"))

df_target_variables= pd.concat([numeric_target_variables, category_target_variables], axis=1)
print(df_target_variables.head(3).to_markdown(index=False, numalign="left"))

#Combine all converted varaibles
combined_df = pd.concat([df_target_variables, df_categorical_variables, df_continuous_variables, date_variables], axis=1)
df = combined_df.copy()  # we use df.copy() so as not to overdefine the previous df
print(df.head(3).to_markdown(index=False, numalign="left"))

df.info()

"""### 1.2. Missing values"""

# Handling missing values
df.isnull().sum()

"""Identify the missing values: Lab_abnormality Flag.
We have three steps: 1. Root cause (human error, system error, functional error)2. replace the value with suitable value with the help of client or subject expert, domain expert, Researcher, Internal Business Analyst
3. use (fill.na)  -

#### 1.3. converting to appropriate variables types
"""

# Converting to appropriate variable types
#df['Gender'] = df['Gender'].astype('category')
#df['Race'] = df['Race'].astype('category')
#df['Admission_Type'] = df['Admission_Type'].astype('category')
#df['Insurance_Provider'] = df['Insurance_Provider'].astype('category')
#df['Hospital_Busyness_Flag'] = df['Hospital_Busyness_Flag'].astype('category')
#df['Lab_Abnormality_Flag'] = df['Lab_Abnormality_Flag'].astype('category')
#df['Feedback_Sentiment'] = df['Feedback_Sentiment'].astype('category')
#df['Observation_Time'] = pd.to_datetime(df['Observation_Time'])
#df['Admission_Date'] = pd.to_datetime(df['Admission_Date'])

"""
comments on the missing values: we have missing values in Lab_Abnormality_Flag. However, they are not missing at random.
they are probably the noraml condition of a patient.
We will consider it as a valid missing value. and fill the category as normal.
"""
df['Lab_Abnormality_Flag'] = df['Lab_Abnormality_Flag'].cat.add_categories(['Normal'])

# Step 2: Replace NaN with "Normal"
df['Lab_Abnormality_Flag'] = df['Lab_Abnormality_Flag'].fillna('Normal')

# Step 3: Verify
print(df['Lab_Abnormality_Flag'].dtype)          # should show 'category'
print(df['Lab_Abnormality_Flag'].cat.categories) # should now include 'Normal'
print(df['Lab_Abnormality_Flag'].value_counts()) # see counts per category

# To keep the confidentiality, it's worth dropping Patient_ID
#df.drop('Patient_ID','DOB', 'Postal_Code', axis=1, inplace=True)

df = df.copy()
print(df.head(3))

df.info()

""" Exporting the combined file for the further use"""

df.to_csv('combined_data.csv', index=False)

"""##1.4. Univariate Analysis

In our research, we are particularly interested in few things.
if the variate is continous or discrete, if we look

for mean = median= mode
 ( -is a desirable output to a data perfect to be normalized.)

for Categorical: We just check for Mode and counts.
"""

import seaborn as sns
mean_Risk_Score = df['Risk_Score'].mean()
median_Risk_Score = df['Risk_Score'].median()
mode_Risk_Score= df['Risk_Score'].mode().values[0]
print(f"Mean Risk Score: {mean_Risk_Score}" )
print(f"Median Risk Score: {median_Risk_Score}")
print(f"Mode Risk Score: {mode_Risk_Score}")

# Distribution plot
sns.displot(df['Risk_Score'], kind = 'kde')

mean_LOS_Days = df['LOS_Days'].mean()
median_LOS_Days = df['LOS_Days'].median()
mode_LOS_Days= df['LOS_Days'].mode().values[0]
print(f"Mean LOS Days: {mean_LOS_Days}")
print(f"Median LOS Days: {median_LOS_Days}")
print(f"Mode LOS Days: {mode_LOS_Days}")

std_LOS_Days = df['LOS_Days'].std()
print(f"std of LOS Days: {std_LOS_Days }")

# Distribution plot
sns.displot(df['LOS_Days'], kind = 'kde')

#df['Patient_Satisfaction_Score'].dtype
sns.displot(df['Patient_Satisfaction_Score'], kind = 'kde')

sns.histplot(df['Patient_Satisfaction_Score'], bins=10, discrete=True)

sns.countplot(x=df['Patient_Satisfaction_Score'])

"""The count is uniformly distributed. This is error of the distribution because of artificially created dateset. So no further investigation could be done."""

df.columns

df['High_Risk_Flag'].dtype
sns.countplot(df['High_Risk_Flag'])

""" it seems to have uneven risk distribution.
"""

sns.countplot(df['Expected_LOS_Category'])

sns.countplot(df['Lab_Abnormality_Flag'])

sns.countplot(df['Gender'])

sns.countplot(x = 'Race', data = df)

sns.countplot(x = 'Admission_Type', data = df)

sns.countplot(x ='Insurance_Provider', data = df)

sns.countplot(df['Hospital_Busyness_Flag'])

sns.countplot(x = 'Feedback_Sentiment', data = df)

mean_Age_at_Admission = df['Age_at_Admission'].mean()
median_Age_at_Admission = df['Age_at_Admission'].median()
mode_Age_at_Admission= df['Age_at_Admission'].mode().values[0]

print(f"Mean Age at Admission: {mean_Age_at_Admission}")
print(f"Median Age at Admission: {median_Age_at_Admission}")
print(f"Mode Age at Admission: {mode_Age_at_Admission}")

std_Age_at_Admission = df['Age_at_Admission'].std()
print(f"std of Age at Admission: {std_Age_at_Admission }")

# Distribution plot

sns.displot(df['Age_at_Admission'], kind = 'kde')

print(df['Available_Beds_Hospital'].dtype)

mean_Available_Beds_Hospital = df['Available_Beds_Hospital'].mean()
median_Available_Beds_Hospital = df['Available_Beds_Hospital'].median()
mode_Available_Beds= df['Available_Beds_Hospital'].mode().values[0]

print(f"mean of Available hospital beds: {mean_Available_Beds_Hospital}")
print(f"Median of Available hospialt beds: {median_Available_Beds_Hospital}")
print(f" Mode of Available hospital beds: {mode_Available_Beds}")

# Distribution plot
sns.displot(df['Available_Beds_Hospital'], kind = 'kde')

print(df['Bed_Occupancy_Rate'].dtype)

mean_Bed_Occupancy_Rate = df['Bed_Occupancy_Rate'].mean()
median_Bed_Occupancy_Rate = df['Bed_Occupancy_Rate'].median()
mode_Bed_Occupancy_Rate = df['Bed_Occupancy_Rate'].mode().values[0]

print(f"mean_Bed_Occupancy_Rate: {mean_Bed_Occupancy_Rate}")
print(f"median_Bed_Occupancy_Rate: {median_Bed_Occupancy_Rate}")
print(f"mode_Bed_Occupancy_Rate: {mode_Bed_Occupancy_Rate}")

print("std: ", df['Bed_Occupancy_Rate'].std())

# Distribution plot
sns.displot(df['Bed_Occupancy_Rate'], kind = 'kde')

df['Comorbidity_Count'].dtype

mean_Comorbidity_Count = df['Comorbidity_Count'].mean()
median_Comorbidity_Count = df['Comorbidity_Count'].median()
mode_Comorbidity_Count = df['Comorbidity_Count'].mode().values[0]

print(f"mean_Comorbidity_Count: {mean_Comorbidity_Count}")
print(f"median_Comorbidity_Count: {median_Comorbidity_Count}")
print(f"mode_Comorbidity_Count: {mode_Comorbidity_Count}")

print("std: ", df['Comorbidity_Count'].std())

# Distribution plot
sns.displot(df['Comorbidity_Count'], kind = 'kde')

df['Pulse_Rate_BPM'].dtype

mean_Pulse_Rate_BPM = df['Pulse_Rate_BPM'].mean()
median_Pulse_Rate_BPM = df['Pulse_Rate_BPM'].median()
mode_Pulse_Rate_BPM = df['Pulse_Rate_BPM'].mode().values[0]

print(f"mean of Pulse_Rate_BPM: {mean_Pulse_Rate_BPM}")
print(f"Median of Pulse_BPM: {median_Pulse_Rate_BPM}")
print(f" Mode of Pulse_BPM : {mode_Pulse_Rate_BPM}")

print("std: ", df['Pulse_Rate_BPM'].std())

# Distribution plot
sns.displot(df['Pulse_Rate_BPM'], kind = 'kde')

df['Systolic_BP_mmHg'].dtype

mean_Systolic_BP_mmHg = df['Systolic_BP_mmHg'].mean()
median_Systolic_BP_mmHg = df['Systolic_BP_mmHg'].median()
mode_Systolic_BP_mmHg = df['Systolic_BP_mmHg'].mode().values[0]

print(f"mean of Systolic_BP_mmHg: {mean_Systolic_BP_mmHg}")
print(f"median of Systolic_BP_mmHg: {median_Systolic_BP_mmHg}")
print(f"mode of Systolic_BP_mmHg: {mode_Systolic_BP_mmHg}")

print("std: ", df['Systolic_BP_mmHg'].std())

# Distribution plot
sns.displot(df['Systolic_BP_mmHg'], kind = 'kde')

df['Respiratory_Rate_per_min'].dtype

mean_Respiratory_Rate_per_min = df['Respiratory_Rate_per_min'].mean()
median_Respiratory_Rate_per_min = df['Respiratory_Rate_per_min'].median()
mode_Respiratory_Rate_per_min = df['Respiratory_Rate_per_min'].mode().values[0]

print(f"Respiratory_Rate_per_min: {mean_Respiratory_Rate_per_min}")
print(f"median of RespiratoryRate per min: {median_Respiratory_Rate_per_min}")
print(f"mode of Respiratory_Rate_per_min: {mode_Respiratory_Rate_per_min}")

print("std: ", df['Respiratory_Rate_per_min'].std())

# Distribution plot
sns.displot(df['Respiratory_Rate_per_min'], kind = 'kde')

print(df['SpO2_percent'].dtype)

mean_SpO2_percent = df['SpO2_percent'].mean()
median_SpO2_percent = df['SpO2_percent'].median()
mode_SpO2_percent = df['SpO2_percent'].mode().values[0]

print(f"mean of SpO2_percent: {mean_SpO2_percent}")
print(f"median of SpO2_percent: {median_SpO2_percent}")
print(f"mode of SpO2_percent: {mode_SpO2_percent}")

print("std: ", df['SpO2_percent'].std())

# Distribution plot
sns.displot(df['SpO2_percent'], kind = 'kde')

from numpy._core.fromnumeric import mean
print(df['Temperature_C'].dtype)

mean_Temperature_C = df['Temperature_C'].mean()
median_Temperature_C = df['Temperature_C'].median()
mode_Temperature_C = df['Temperature_C'].mode().values[0]

print(f"mean of Temperature_C: {mean_Temperature_C}")
print(f"median of Temperature_C: {median_Temperature_C}")
print(f"mode of Temperature_C: {mode_Temperature_C}")

print("std: ", df['Temperature_C'].std())

# distribution plot
sns.displot(df['Temperature_C'], kind = 'kde')

df.columns

print(df['Sodium_mEq_L'].dtype)
sns.displot(df['Sodium_mEq_L'], kind = 'kde')

print(df['Creatinine_mg_dL'].dtype)
sns.displot(df['Creatinine_mg_dL'], kind = 'kde')

print(df['Platelets_k_uL'].dtype)
sns.displot(df['Platelets_k_uL'], kind = 'kde')

print(df['Glucose_randam_mg_dL'].dtype)
sns.displot(df['Glucose_randam_mg_dL'], kind = 'kde')

print(df['Glucose_adparadiam_mg_dL'].dtype)
sns.displot(df['Glucose_adparadiam_mg_dL'], kind = 'kde')

print(df['Glucose_postparadian_mg_dL'].dtype)
sns.displot(df['Glucose_postparadian_mg_dL'], kind = 'kde')

print(df['WBC_count_x10_9_L'].dtype)
sns.displot(df['WBC_count_x10_9_L'], kind = 'kde')

print(df['Severity_Score_Encounter'].dtype)
sns.displot(df['Severity_Score_Encounter'], kind = 'kde')

print(df['Admission_Date'].dtype)
sns.displot(df['Admission_Date'], kind = 'kde')

print(df['Encounter_Date'].dtype)
sns.displot(df['Encounter_Date'], kind = 'kde')

print(df['Discharge_Date'].dtype)
sns.displot(df['Discharge_Date'], kind = 'kde')

"""##1.4.2. Bivariate Analysis"""

print("Data Type of Comorbidity:", df['Comorbidity_Count'].dtype)
sns.relplot(data=df, y ="Risk_Score", x ="Comorbidity_Count")

sns.relplot(data=df, x="Risk_Score", y="LOS_Days")

#sns.relplot(data=df, x="Risk_Score", y="Patient_Satisfaction_Score")

sns.relplot(data=df, y="Risk_Score", x="Age_at_Admission")

#sns.relplot(data=df, y="Risk_Score", x="Age_at_Admission", hue = "Gender")

#sns.relplot(data=df, y="Risk_Score", x="Age_at_Admission", hue = "Race")

#sns.relplot(data=df, y="Risk_Score", x="Pulse_Rate_BPM")

#sns.relplot(data=df, y="Risk_Score", x="Systolic_BP_mmHg")

#sns.relplot(data=df, y="Risk_Score", x ="Diastolic_BP_mmHg")

#sns.relplot(data=df, y ="Risk_Score", x ="Respiratory_Rate_per_min")

#sns.relplot(data=df, x="Risk_Score", y="SpO2_percent")

#sns.relplot(data=df, x="Risk_Score", y="Temperature_C")

#sns.relplot(data=df, x="Risk_Score", y="Sodium_mEq_L")

#sns.relplot(data = df, x= "Risk_Score", y = "Creatinine_mg_dL")

"""###1.4.3. Multivariate relation"""

pal = dict(Male ="green", Female =".5", Other = ".8")
g = sns.FacetGrid(df, hue="Gender", palette=pal, height=5)
g.map(sns.scatterplot, "Age_at_Admission", "Risk_Score", s=100, alpha=.5)
g.add_legend()

g = sns.FacetGrid(df, col="Gender", hue="Race")
g.map(sns.scatterplot, "Age_at_Admission", "Risk_Score", alpha=.7)
g.add_legend()

#g = sns.PairGrid(df)
#g.map(sns.scatterplot)

#g = sns.PairGrid(df)
#g.map_diag(sns.histplot)
#g.map_offdiag(sns.scatterplot)

"""##1.4.2. Profiling the dataset and understanding the distribution of the variables

"""

!pip install ydata-profiling

from ydata_profiling import ProfileReport
profile = ProfileReport(df, title="Pandas Profiling Report")
df.profile_report()

html_str = profile.to_html()
with open("data_report.html", "w", encoding="utf-8") as f:
    f.write(html_str)